import 'package:dealos_mobile/features/workspace/domain/models.dart';

Workspace fixtureWorkspace({String role = 'MANAGER', List<String>? modules}) =>
    Workspace.fromJson({
      'user': {
        'id': 'user-1',
        'name': role == 'CUSTOMER' ? 'Portal User' : 'Maya Manager',
        'email': 'maya@example.com',
        'role': role,
        'customerId': role == 'CUSTOMER' ? 'customer-1' : null,
        'organizationId': 'org-1',
        'moduleAccess':
            modules ??
            [
              'dashboard',
              'quotations',
              'approvals',
              'fulfillment',
              'invoices',
              'reports',
              'health',
            ],
        'actorType': 'USER',
        'platformSuperAdmin': false,
        'readOnlyView': false,
      },
      'organization': {'id': 'org-1', 'name': 'Acme Systems'},
      'users': [],
      'customers': [
        {
          'id': 'customer-1',
          'name': 'Vertex Systems',
          'tier': 'Gold',
          'currency': 'INR',
          'active': true,
          'email': 'buyer@vertex.test',
        },
      ],
      'products': [
        {
          'id': 'product-1',
          'name': 'Edge Server',
          'sku': 'EDGE-1',
          'category': 'Hardware',
          'description': 'Compute appliance',
          'unit': 'Piece',
          'price': '125000',
          'cost': '82000',
          'taxRate': '18',
          'recurring': false,
          'active': true,
          'stocks': [],
        },
      ],
      'quotes': [
        {
          'id': 'quote-1',
          'number': 'Q-1001',
          'customer': 'Vertex Systems',
          'customerTier': 'Gold',
          'stage': 'PENDING_APPROVAL',
          'version': 2,
          'orderDiscount': '0',
          'total': '147500',
          'margin': '43000',
          'riskScore': '4',
          'updatedAt': '2026-09-05T10:00:00Z',
          'owner': {'id': 'rep-1', 'name': 'Ravi Rep'},
          'lines': [
            {
              'id': 'line-1',
              'productId': 'product-1',
              'quantity': 1,
              'unitPrice': '125000',
              'unitCost': '82000',
              'discount': '2',
              'allowedDiscount': '1',
              'product': {
                'id': 'product-1',
                'name': 'Edge Server',
                'sku': 'EDGE-1',
                'category': 'Hardware',
                'description': 'Compute appliance',
                'unit': 'Piece',
                'price': '125000',
                'cost': '82000',
                'taxRate': '18',
                'recurring': false,
                'active': true,
                'stocks': [],
              },
            },
          ],
          'approvals': [
            {
              'id': 'approval-1',
              'step': 'Sales Manager',
              'sequence': 1,
              'state': 'PENDING',
            },
          ],
          'negotiation': [],
          'invoices': [],
        },
      ],
      'policies': [],
      'warehouses': [],
      'subscriptions': [],
      'invoices': [
        {
          'id': 'invoice-1',
          'number': 'INV-1',
          'customer': 'Vertex Systems',
          'amount': '147500',
          'paidAmount': '0',
          'state': 'UNPAID',
          'dueAt': '2026-10-05T00:00:00Z',
          'lines': [],
          'payments': [],
        },
      ],
      'alerts': [],
      'audits': [],
    });
