import { useEffect, useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, FilePlus2, Inbox, RefreshCw, Search, XCircle } from 'lucide-react';
import { request, type Lead } from '../../api';
import './leads.css';

type LeadStatus = 'NEW'|'CONVERTED'|'DISMISSED';

export function LeadsPage({role,openQuote,initialLeadId}:{role:string;openQuote:(id:string,revisionId?:string|null)=>void;initialLeadId?:string}) {
  const [status,setStatus]=useState<LeadStatus|'ALL'>('NEW');
  const [items,setItems]=useState<Lead[]>([]);
  const [selected,setSelected]=useState<Lead|null>(null);
  const [search,setSearch]=useState('');
  const [loading,setLoading]=useState(true);
  const [working,setWorking]=useState(false);
  const [error,setError]=useState('');
  const [dismissOpen,setDismissOpen]=useState(false);

  const load=async()=>{setLoading(true);setError('');try{const result=await request<{items:Lead[]}>(`/leads${status==='ALL'?'':`?status=${status}`}`);setItems(result.items);setSelected(current=>result.items.find(item=>item.id===(current?.id??initialLeadId))??null)}catch(cause){setError(cause instanceof Error?cause.message:'Could not load Leads.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[status,initialLeadId]);
  const visible=items.filter(lead=>`${lead.customer.name} ${lead.requirementsSummary} ${lead.assignedRep.name}`.toLowerCase().includes(search.toLowerCase()));
  const convert=async()=>{if(!selected)return;setWorking(true);setError('');try{const result=await request<{quotation:{id:string;revisionId?:string};replayed:boolean}>(`/leads/${selected.id}/convert`,{method:'POST',body:'{}'});await load();openQuote(result.quotation.id,result.quotation.revisionId)}catch(cause){setError(cause instanceof Error?cause.message:'Could not convert the Lead.')}finally{setWorking(false)}};
  const dismiss=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const reason=String(new FormData(event.currentTarget).get('reason')??'');setWorking(true);setError('');try{await request(`/leads/${selected.id}/dismiss`,{method:'POST',body:JSON.stringify({reason})});setDismissOpen(false);setSelected(null);await load()}catch(cause){setError(cause instanceof Error?cause.message:'Could not dismiss the Lead.')}finally{setWorking(false)}};

  return <section className="leads-page" aria-labelledby="leads-title">
    <div className="module-intro"><div><h2 id="leads-title">Portal Leads</h2><p>Qualify customer-originated requests before a commercial quotation exists.</p></div><span className="lead-mode-note">Lead-first intake</span></div>
    <div className="leads-toolbar"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search customer, requirement, or representative"/></label><div role="group" aria-label="Lead status">{(['NEW','CONVERTED','DISMISSED','ALL'] as const).map(value=><button key={value} className={status===value?'active':''} onClick={()=>setStatus(value)}>{value==='ALL'?'All':value.toLowerCase()}</button>)}</div></div>
    {error&&<div className="leads-error" role="alert"><AlertTriangle/>{error}<button onClick={load}>Retry</button></div>}
    <div className="leads-layout"><div className="leads-list">{loading?<div className="leads-loading"><RefreshCw className="spin"/>Loading Leads…</div>:visible.length?visible.map(lead=><button key={lead.id} className={selected?.id===lead.id?'active':''} onClick={()=>setSelected(lead)}><span><small>{lead.customer.name}</small><b>{lead.requirementsSummary}</b></span><span className={`lead-status ${lead.status.toLowerCase()}`}>{lead.status}</span><em>{lead.assignedRep.name}<ChevronRight/></em></button>):<div className="leads-empty"><Inbox/><h3>No Leads here</h3><p>Customer portal requests in Lead-first mode will appear for their assigned representative.</p></div>}</div><div className="lead-detail">{selected?<><div className="lead-detail-head"><div><span className={`lead-status ${selected.status.toLowerCase()}`}>{selected.status}</span><h3>{selected.customer.name}</h3><p>{selected.team?.name??'No current team'} · Assigned to {selected.assignedRep.name}</p></div><small>{new Date(selected.createdAt).toLocaleString()}</small></div><section><h4>Customer requirements</h4><p>{selected.request.requirementsText}</p>{selected.request.preferredDeliveryDate&&<p><b>Preferred delivery:</b> {new Date(selected.request.preferredDeliveryDate).toLocaleDateString()}</p>}</section><section><h4>Requested items</h4>{selected.request.lines.length?<div className="lead-lines">{selected.request.lines.map(line=><article key={line.id} className={line.degraded?'degraded':''}><div><b>{line.product?.name??line.freeTextDescription??'Unmatched item'}</b><small>{line.product?.sku??'Customer description'}{line.quantity?` · Qty ${line.quantity}`:''}</small></div>{line.degraded&&<span><AlertTriangle/>Catalog match unavailable — review manually</span>}</article>)}</div>:<p className="muted">No structured items; use the requirements text when preparing the quotation.</p>}</section>{selected.status==='NEW'&&<div className="lead-actions">{role==='REP'&&<button className="button primary" onClick={convert} disabled={working}><FilePlus2/>{working?'Converting…':'Convert to quotation'}</button>}<button className="button ghost" onClick={()=>setDismissOpen(true)} disabled={working}><XCircle/>Dismiss</button></div>}{selected.convertedQuotation&&<button className="button primary" onClick={()=>openQuote(selected.convertedQuotation!.id)}>Open {selected.convertedQuotation.number}<ChevronRight/></button>}{selected.status==='DISMISSED'&&<div className="lead-dismissed"><b>Internal dismissal reason</b><p>{selected.dismissReason}</p></div>}</>:<div className="lead-detail-empty"><Inbox/><h3>Select a Lead</h3><p>Review the original request, catalog matches, and next action.</p></div>}</div></div>
    {dismissOpen&&selected&&<div className="modal-wrap"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="dismiss-lead-title"><div className="panel-title"><h3 id="dismiss-lead-title">Dismiss Lead</h3><button aria-label="Close dismiss Lead" onClick={()=>setDismissOpen(false)}>×</button></div><form className="form" onSubmit={dismiss}><p className="muted">The customer will see only that the request is not being progressed. This internal reason is never shown verbatim.</p><label>Internal reason<textarea name="reason" required minLength={5} maxLength={1000}/></label><button className="button danger" disabled={working}>{working?'Saving…':'Dismiss Lead'}</button></form></div></div>}
  </section>;
}
