import { beforeEach, describe, it, expect, vi } from 'vitest';
const findUnique=vi.fn(async () => null);
const createOrganization=vi.fn(async (_input: object) => ({id:'org-1',name:'Acme',slug:'acme-test'}));
const createUser=vi.fn(async (input: any) => ({id:'admin-1',...input.data}));
const createMembership=vi.fn(async (input: any) => ({id:'membership-1',...input.data}));
const transaction=vi.fn(async (callback: Function) => callback({organization:{create:createOrganization},user:{create:createUser},organizationMembership:{create:createMembership}}));
const verifyIdToken=vi.fn();
vi.mock('../src/db.js',()=>({db:{$transaction:transaction,user:{findUnique}}}));
vi.mock('google-auth-library',()=>({OAuth2Client:class { verifyIdToken=verifyIdToken; }}));
describe('public signup',()=>{
 beforeEach(()=>{findUnique.mockReset();findUnique.mockResolvedValue(null);createOrganization.mockClear();createUser.mockClear();createMembership.mockClear();transaction.mockClear();});
 it('rejects role and access injection, short passwords and blank names',async()=>{const {googleSignupSchema,signupSchema}=await import('../src/identity.js');const valid={organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!'};expect(signupSchema.safeParse({...valid,role:'ADMIN'}).success).toBe(false);expect(signupSchema.safeParse({...valid,moduleAccess:['reports']}).success).toBe(false);expect(signupSchema.safeParse({...valid,password:'short'}).success).toBe(false);expect(signupSchema.safeParse({...valid,displayName:'  '}).success).toBe(false);expect(signupSchema.parse({...valid,email:' ALEX@example.com '}).email).toBe('alex@example.com');expect(googleSignupSchema.safeParse({credential:'token',organizationName:'Acme',role:'ADMIN'}).success).toBe(false);});
 it('creates the first identity as an active organization admin',async()=>{const {createOrganizationAdmin}=await import('../src/identity.js');await createOrganizationAdmin({organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!'});const organizationData=createOrganization.mock.calls[0]![0] as any;const userData=createUser.mock.calls[0]![0] as any;expect(organizationData.data).toMatchObject({name:'Acme'});expect(organizationData.data.slug).toMatch(/^acme-/);expect(userData.data).toMatchObject({organizationId:'org-1',email:'alex@example.com',role:'ADMIN',status:'ACTIVE',moduleAccess:[]});expect(userData.data.passwordHash).not.toBe('LongPassword12!');expect(createMembership).toHaveBeenCalledWith({data:{organizationId:'org-1',userId:'admin-1',accessRole:'ORGANIZATION_ADMIN',businessRole:'ADMIN'}});const bcrypt=await import('bcryptjs');expect(await bcrypt.compare('LongPassword12!',userData.data.passwordHash)).toBe(true);});
 it('verifies Google and creates an active linked organization admin',async()=>{const {createGoogleOrganizationAdmin,verifyGoogleSignupCredential}=await import('../src/identity.js');verifyIdToken.mockResolvedValueOnce({getPayload:()=>({sub:'google-subject',email:'alex@example.com',email_verified:false})});await expect(verifyGoogleSignupCredential('unverified-token','client-id')).rejects.toThrow('verified email');verifyIdToken.mockResolvedValue({getPayload:()=>({sub:'google-subject',email:' Alex@Example.com ',email_verified:true,name:'Alex Google'})});const profile=await verifyGoogleSignupCredential('signed-google-token','client-id');expect(profile).toEqual({subject:'google-subject',displayName:'Alex Google',email:'alex@example.com'});await createGoogleOrganizationAdmin(profile,'Acme');const data=createUser.mock.calls.at(-1)![0] as any;expect(data.data).toMatchObject({email:'alex@example.com',googleSubject:'google-subject',role:'ADMIN',status:'ACTIVE'});});
});
