import { beforeEach, describe, it, expect, vi } from 'vitest';
const findUnique=vi.fn(async () => null);
const createOrganization=vi.fn(async (_input: object) => ({id:'org-1',users:[{id:'admin-1'}]}));
const verifyIdToken=vi.fn();
vi.mock('../src/db.js',()=>({db:{user:{findUnique},organization:{create:createOrganization}}}));
vi.mock('google-auth-library',()=>({OAuth2Client:class { verifyIdToken=verifyIdToken; }}));
describe('public signup',()=>{
 beforeEach(()=>{findUnique.mockReset();findUnique.mockResolvedValue(null);createOrganization.mockClear();});
 it('rejects role and access injection, short passwords and blank names',async()=>{const {googleSignupSchema,signupSchema}=await import('../src/identity.js');const valid={organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!'};expect(signupSchema.safeParse({...valid,role:'ADMIN'}).success).toBe(false);expect(signupSchema.safeParse({...valid,moduleAccess:['reports']}).success).toBe(false);expect(signupSchema.safeParse({...valid,password:'short'}).success).toBe(false);expect(signupSchema.safeParse({...valid,displayName:'  '}).success).toBe(false);expect(signupSchema.parse({...valid,email:' ALEX@example.com '}).email).toBe('alex@example.com');expect(googleSignupSchema.safeParse({credential:'token',organizationName:'Acme',role:'ADMIN'}).success).toBe(false);});
 it('creates the first identity as an active organization admin',async()=>{const {createOrganizationAdmin}=await import('../src/identity.js');await createOrganizationAdmin({organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!'});const data=createOrganization.mock.calls[0]![0] as any;expect(data.data.name).toBe('Acme');expect(data.data.users.create).toMatchObject({email:'alex@example.com',role:'ADMIN',status:'ACTIVE',moduleAccess:[]});expect(data.data.users.create.passwordHash).not.toBe('LongPassword12!');const bcrypt=await import('bcryptjs');expect(await bcrypt.compare('LongPassword12!',data.data.users.create.passwordHash)).toBe(true);});
 it('verifies Google and creates an active linked organization admin',async()=>{const {createGoogleOrganizationAdmin,verifyGoogleSignupCredential}=await import('../src/identity.js');verifyIdToken.mockResolvedValueOnce({getPayload:()=>({sub:'google-subject',email:'alex@example.com',email_verified:false})});await expect(verifyGoogleSignupCredential('unverified-token','client-id')).rejects.toThrow('verified email');verifyIdToken.mockResolvedValue({getPayload:()=>({sub:'google-subject',email:' Alex@Example.com ',email_verified:true,name:'Alex Google'})});const profile=await verifyGoogleSignupCredential('signed-google-token','client-id');expect(profile).toEqual({subject:'google-subject',displayName:'Alex Google',email:'alex@example.com'});await createGoogleOrganizationAdmin(profile,'Acme');const data=createOrganization.mock.calls.at(-1)![0] as any;expect(data.data.users.create).toMatchObject({email:'alex@example.com',googleSubject:'google-subject',role:'ADMIN',status:'ACTIVE'});});
});
