import { beforeEach, describe, it, expect, vi } from 'vitest';
const findUnique=vi.fn(async () => null);
const createOrganization=vi.fn(async (_input: object) => ({}));
const upsert=vi.fn(async (_input: {update: object; create: {role:string; status:string; passwordHash:string}}) => ({}));
const verifyIdToken=vi.fn();
vi.mock('../src/db.js',()=>({db:{user:{findUnique,upsert},organization:{create:createOrganization}}}));
vi.mock('google-auth-library',()=>({OAuth2Client:class { verifyIdToken=verifyIdToken; }}));
describe('public signup',()=>{
 beforeEach(()=>{findUnique.mockReset();findUnique.mockResolvedValue(null);createOrganization.mockClear();upsert.mockClear();});
 it('rejects role injection, invalid access roles, short passwords and blank names',async()=>{const {googleSignupSchema,signupSchema}=await import('../src/identity.js');const valid={organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!',users:[]};expect(signupSchema.safeParse({...valid,role:'ADMIN'}).success).toBe(false);expect(signupSchema.safeParse({...valid,password:'short'}).success).toBe(false);expect(signupSchema.safeParse({...valid,displayName:'  '}).success).toBe(false);expect(signupSchema.safeParse({...valid,users:[{email:'user@example.com',role:'ADMIN'}]}).success).toBe(false);expect(signupSchema.parse({...valid,email:' ALEX@example.com '}).email).toBe('alex@example.com');expect(googleSignupSchema.safeParse({credential:'token',role:'ADMIN'}).success).toBe(false);});
 it('creates an active organization admin with durable role-based invitations',async()=>{const {createOrganizationAdmin}=await import('../src/identity.js');await createOrganizationAdmin({organizationName:'Acme',displayName:'Alex',email:'alex@example.com',password:'LongPassword12!',users:[{email:'rep@example.com',role:'REP'}]});const data=createOrganization.mock.calls[0]![0] as any;expect(data.data.name).toBe('Acme');expect(data.data.users.create).toMatchObject({email:'alex@example.com',role:'ADMIN',status:'ACTIVE'});expect(data.data.invites.create).toEqual([{email:'rep@example.com',role:'REP'}]);expect(data.data.users.create.passwordHash).not.toBe('LongPassword12!');const bcrypt=await import('bcryptjs');expect(await bcrypt.compare('LongPassword12!',data.data.users.create.passwordHash)).toBe(true);});
 it('verifies Google audience and creates a duplicate-safe pending account',async()=>{const {createPendingGoogleAccount,verifyGoogleSignupCredential}=await import('../src/identity.js');verifyIdToken.mockResolvedValueOnce({getPayload:()=>({sub:'google-subject',email:'alex@example.com',email_verified:false})});await expect(verifyGoogleSignupCredential('unverified-token','client-id')).rejects.toThrow('verified email');verifyIdToken.mockResolvedValue({getPayload:()=>({sub:'google-subject',email:' Alex@Example.com ',email_verified:true,name:'Alex Google'})});const profile=await verifyGoogleSignupCredential('signed-google-token','client-id');expect(verifyIdToken).toHaveBeenCalledWith({idToken:'signed-google-token',audience:'client-id'});expect(profile).toEqual({subject:'google-subject',displayName:'Alex Google',email:'alex@example.com'});await createPendingGoogleAccount(profile);const data=upsert.mock.calls.at(-1)![0];expect(data.update).toEqual({});expect(data.create).toMatchObject({email:'alex@example.com',name:'Alex Google',role:'REP',status:'PENDING'});expect(data.create.passwordHash).not.toBe('signed-google-token');});
});
