ALTER TABLE "Product" ADD COLUMN "storeVisible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Product" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "StockBalance" ADD COLUMN "minAlertLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "StockBalance" ADD COLUMN "maxCapacity" INTEGER;
