import { useLayoutEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, AudioWaveform, Boxes, Check, FileText, Menu, Mic, Pause, Play, Radio, ReceiptText, ShieldCheck, Sparkles, Smartphone, X, Zap } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { Brand } from "./Brand";
import "./motion.css";

gsap.registerPlugin(ScrollTrigger);

const states = [
  { label: "Build", title: "The commercial truth,\nin one place.", copy: "Products, quantities, one-time charges, recurring plans, discount policy, and live margin—resolved before the quote leaves the desk.", icon: FileText, meta: "Revision 06 · Draft" },
  { label: "Govern", title: "Exceptions find\nthe right reviewer.", copy: "Every line is checked against its own ceiling. DealOS explains the exception, preserves the reason, and routes the exact revision.", icon: ShieldCheck, meta: "2 approvals · In sequence" },
  { label: "Commit", title: "Promises meet\nreal inventory.", copy: "Available stock, shipment count, and warehouse cost become one practical allocation—with shortages shown before anyone over-promises.", icon: Boxes, meta: "2 warehouses · 0 hidden gaps" },
  { label: "Settle", title: "One order. Two\nbilling rhythms.", copy: "One-time products and recurring subscriptions stay distinct, while invoices, schedules, credits, and verified payments remain connected.", icon: ReceiptText, meta: "Invoice + annual plan" },
];

function DealFrame({ compact = false }: { compact?: boolean }) {
  return <div className={`deal-frame ${compact ? "compact" : ""}`}>
    <div className="frame-bar"><span className="frame-brand"><img src="/images/dealos-logo.png" alt="DealOS" /></span><span className="frame-state"><i /> Pending approval</span></div>
    <div className="frame-head"><div><small>QUOTATION Q-1048</small><strong>Aranya Systems</strong></div><b>₹1,28,64,000</b></div>
    <div className="frame-lines"><div><span>Edge workstation</span><small>24 units</small><b>₹92,16,000</b></div><div><span>Deployment service</span><small>1 project</small><b>₹24,00,000</b></div><div><span>Priority support</span><small>Annual</small><b>₹12,48,000</b></div></div>
    <div className="frame-risk"><span><ShieldCheck /> Policy check</span><p>Service discount is <b>8 points</b> above its category ceiling.</p><strong>Manager → Finance</strong></div>
  </div>;
}

function StatePanel({ index }: { index: number }) {
  const state = states[index]; const Icon = state.icon;
  return <div className="state-panel" aria-live="polite">
    <div className="state-panel-top"><span>LIVE DEAL / Q-1048</span><Icon /></div>
    {index === 0 && <DealFrame compact />}
    {index === 1 && <div className="approval-ui"><div className="approval-score"><small>WORST LINE EXCESS</small><strong>8.0</strong><span>percentage points</span></div><div className="approval-route"><span className="done"><i><Check /></i><b>Sales Manager</b><small>Approved · 10:24</small></span><em /><span><i>02</i><b>Finance</b><small>Reason required</small></span></div><p>Exact revision, policy version, reviewer, time, and reason travel together.</p></div>}
    {index === 2 && <div className="allocation-ui"><div className="warehouse"><i>01</i><span><b>Mumbai warehouse</b><small>18 workstations</small></span><strong>₹18,400</strong></div><div className="route-line"><span /><i /><span /></div><div className="warehouse"><i>02</i><span><b>Pune depot</b><small>6 workstations</small></span><strong>₹8,900</strong></div><div className="allocation-total"><span>Suggested split</span><b>2 shipments · ₹27,300</b></div></div>}
    {index === 3 && <div className="billing-ui"><div><small>ONE-TIME</small><strong>₹1,16,16,000</strong><span>Due 04 Oct</span></div><div><small>RECURRING</small><strong>₹1,04,000<em>/mo</em></strong><span>Next bill 04 Nov</span></div><p><ReceiptText /> Payment evidence and balances remain auditable.</p></div>}
    <div className="state-panel-foot"><span>{state.meta}</span><span>0{index + 1} / 04</span></div>
  </div>;
}

export function Landing() {
  const root = useRef<HTMLDivElement>(null); const [menu, setMenu] = useState(false); const [paused, setPaused] = useState(false); const [active, setActive] = useState(0); const [listening, setListening] = useState(false);
  useLayoutEffect(() => {
    const mm = gsap.matchMedia();
    mm.add({ motion: "(prefers-reduced-motion: no-preference)", desktop: "(min-width: 900px)" }, context => {
      if (!context.conditions?.motion || paused) return;
      const ctx = gsap.context(() => {
        gsap.from(".ledger-title span", { yPercent: 115, rotate: 2, stagger: .12, duration: 1, ease: "power4.out" });
        gsap.from(".ledger-kicker, .ledger-hero-foot", { opacity: 0, y: 18, duration: .7, delay: .35, ease: "power2.out" });
        gsap.from(".deal-stack", { opacity: 0, x: 60, rotate: 3, duration: 1.2, delay: .2, ease: "expo.out" });
        gsap.to(".stack-shadow", { yPercent: 22, rotate: -7, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1 } });
        gsap.to(".deal-stack > .deal-frame", { yPercent: -13, rotate: 1.5, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1 } });
        gsap.to(".hero-grid", { yPercent: 15, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1.4 } });
        gsap.to(".hero-outline", { yPercent: -18, rotate: 4, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1.2 } });
        gsap.to(".stack-note", { yPercent: -55, rotate: -2, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1 } });
        gsap.to(".stack-audit", { yPercent: 55, rotate: 6, ease: "none", scrollTrigger: { trigger: ".ledger-hero", start: "top top", end: "bottom top", scrub: 1.35 } });
        gsap.to(".operations-band-track", { xPercent: -18, ease: "none", scrollTrigger: { trigger: ".operations-band", start: "top bottom", end: "bottom top", scrub: 1 } });
        gsap.utils.toArray<HTMLElement>(".problem-card").forEach((card, index) => gsap.from(card, { y: 55 + index * 12, opacity: 0, rotate: index % 2 ? 1 : -1, duration: .85, ease: "power3.out", scrollTrigger: { trigger: card, start: "top 88%", once: true } }));
        gsap.utils.toArray<HTMLElement>(".problem-card > i").forEach((ring, index) => gsap.to(ring, { yPercent: 45 + index * 8, rotate: 90, ease: "none", scrollTrigger: { trigger: ring.parentElement, start: "top bottom", end: "bottom top", scrub: 1 } }));
        if (context.conditions?.desktop) {
          const blocks = gsap.utils.toArray<HTMLElement>(".state-copy");
          const story = gsap.timeline({ scrollTrigger: { trigger: ".deal-story", start: "top top", end: "+=3200", pin: true, scrub: .8, anticipatePin: 1, onUpdate: self => setActive(Math.min(3, Math.floor(self.progress * 4))) } });
          blocks.forEach((block, index) => { if (!index) return; story.fromTo(block, { autoAlpha: 0, y: 60 }, { autoAlpha: 1, y: 0, duration: .35 }, index); story.to(blocks[index - 1], { autoAlpha: 0, y: -45, duration: .28 }, index - .25); });
          story.to(".story-depth-one", { x: -48, y: 38, rotate: -7, duration: 3.7, ease: "none" }, 0).to(".story-depth-two", { x: 54, y: -36, rotate: 8, duration: 3.7, ease: "none" }, 0);
        }
        gsap.utils.toArray<HTMLElement>(".proof-frame").forEach((frame, index) => gsap.fromTo(frame, { y: index % 2 ? 80 : 35 }, { y: index % 2 ? -35 : -15, ease: "none", scrollTrigger: { trigger: frame, start: "top bottom", end: "bottom top", scrub: 1.1 } }));
        gsap.to(".mobile-product-art", { yPercent: -13, rotate: 1.2, ease: "none", scrollTrigger: { trigger: ".continuity-section", start: "top bottom", end: "bottom top", scrub: 1.1 } });
        gsap.to(".sync-orbit", { rotate: 135, scale: 1.08, ease: "none", scrollTrigger: { trigger: ".continuity-section", start: "top bottom", end: "bottom top", scrub: 1.3 } });
        gsap.to(".voice-disc", { yPercent: -18, rotate: -8, ease: "none", scrollTrigger: { trigger: ".voice-section", start: "top bottom", end: "bottom top", scrub: 1.2 } });
        gsap.utils.toArray<HTMLElement>(".continuity-note").forEach((note, index) => gsap.from(note, { y: 45 + index * 15, opacity: 0, duration: .8, ease: "power3.out", scrollTrigger: { trigger: note, start: "top 88%", once: true } }));
        gsap.fromTo(".audit-progress i", { scaleX: 0 }, { scaleX: 1, ease: "none", scrollTrigger: { trigger: ".audit-section", start: "top 75%", end: "bottom 45%", scrub: 1 } });
        gsap.from(".ledger-outro h2 span", { yPercent: 110, stagger: .12, duration: .9, ease: "power4.out", scrollTrigger: { trigger: ".ledger-outro", start: "top 70%", once: true } });
      }, root); return () => ctx.revert();
    });
    document.fonts?.ready.then(() => ScrollTrigger.refresh()); return () => mm.revert();
  }, [paused]);

  return <div ref={root} className={`ledger-site ${paused ? "motion-paused" : ""}`}>
    <a className="skip-link" href="#content">Skip to content</a>
    <nav className="ledger-nav"><Brand /><div className={`ledger-links ${menu ? "open" : ""}`}><a href="#problem" onClick={() => setMenu(false)}>The problem</a><a href="#system" onClick={() => setMenu(false)}>How it works</a><a href="/directory" onClick={() => setMenu(false)}>Business directory</a><a href="#proof" onClick={() => setMenu(false)}>Inside DealOS</a><a className="mobile-signin" href="/sign-in">Sign in <ArrowUpRight /></a></div><div className="nav-actions"><a className="signin" href="/sign-in">Sign in</a><a className="signal-button small" href="/sign-up">Create organization <ArrowUpRight /></a><button className="menu-button" aria-label={menu ? "Close navigation" : "Open navigation"} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></nav>
    <main id="content">
      <section className="ledger-hero"><div className="hero-grid" aria-hidden="true" /><div className="hero-outline" aria-hidden="true"><span>LIVE / COMMERCIAL RECORD</span><i /><b>Q-1048</b></div><div className="hero-copy"><div className="ledger-kicker"><span>DEAL OPERATIONS / ONE SOURCE OF TRUTH</span><span>EST. 2026</span></div><h1 className="ledger-title" aria-label="The deal is a system. Run it like one."><span>THE DEAL IS</span><span>A SYSTEM<span className="signal-dot">.</span></span><span>RUN IT LIKE ONE.</span></h1><div className="ledger-hero-foot"><p>Quote, govern, commit, and bill from one living commercial record.</p><a className="signal-button" href="/sign-up">Open your deal room <ArrowUpRight /></a><a className="scroll-cue" href="#problem"><ArrowDown /><span>See where deals drift</span></a></div></div><div className="deal-stack" aria-label="Example DealOS quotation"><div className="stack-shadow"><span>REV / 05</span></div><div className="stack-note"><Sparkles /><span>Margin healthy after suggested support plan</span></div><div className="stack-audit"><ShieldCheck /><span>AUDIT READY</span><b>06 events</b></div><DealFrame /></div><div className="hero-index" aria-hidden="true"><span>01</span><i /><span>06</span></div></section>
      <section className="operations-band" aria-label="DealOS workflow"><div className="operations-band-track">{[0,1,2].map(index => <span key={index}>QUOTE <i>↗</i> POLICY <i>↗</i> APPROVAL <i>↗</i> INVENTORY <i>↗</i> BILLING <i>↗</i> AUDIT <i>↗</i></span>)}</div></section>
      <section className="problem-section" id="problem"><div className="section-intro"><span className="section-index">01 / THE HANDOFF PROBLEM</span><h2>Every team has a piece.<br /><em>Nobody has the deal.</em></h2><p>Commercial truth drifts when decisions live in separate tools. DealOS keeps the context attached.</p></div><div className="problem-grid">{[["SALES", "The price changed.", "The approval did not."], ["FINANCE", "The discount arrived.", "The reason did not."], ["OPERATIONS", "The order arrived.", "The stock promise did not."], ["CUSTOMER", "The revision arrived.", "The history did not."]].map(([role, lead, tail], index) => <article className="problem-card" key={role}><span>0{index + 1} · {role}</span><h3>{lead}<br /><em>{tail}</em></h3><i aria-hidden="true" /></article>)}</div></section>
      <section className="deal-story" id="system"><div className="story-copy-wrap"><span className="section-index inverse">02 / ONE LIVING RECORD</span>{states.map((state, index) => <div className={`state-copy ${index === 0 ? "active" : ""}`} key={state.label}><span>0{index + 1} · {state.label}</span><h2>{state.title.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p>{state.copy}</p></div>)}<div className="state-rail" aria-label={`Step ${active + 1} of 4`}>{states.map((state, index) => <span key={state.label} className={index <= active ? "on" : ""}><i />{state.label}</span>)}</div></div><div className="story-visual"><div className="story-depth story-depth-one" aria-hidden="true"><span>POLICY / V3.2</span></div><div className="story-depth story-depth-two" aria-hidden="true"><span>REVISION / 06</span></div><StatePanel index={active} /></div></section>
      <section className="continuity-section" id="continuity"><div className="continuity-copy"><span className="section-index">03 / ONE DEAL, EVERY SURFACE</span><h2>The record moves.<br /><em>The truth stays put.</em></h2><p>Review a revision on desktop, approve it from your phone, and return to the same live context. DealOS synchronizes decisions—not just screens.</p><div className="sync-ledger"><div><Radio /><span><b>Instant state</b><small>Every approved change reaches every surface.</small></span><em>LIVE</em></div><div><ShieldCheck /><span><b>Revision-safe</b><small>Voice, mobile, and web act on the same version.</small></span><em>06</em></div><div><Zap /><span><b>Action-ready</b><small>Open directly to the decision that needs you.</small></span><em>NOW</em></div></div></div><div className="mobile-stage"><div className="sync-orbit" aria-hidden="true"><span>WEB</span><span>VOICE</span><span>MOBILE</span></div><img className="mobile-product-art" src="/images/dealos-mobile-product.png" alt="DealOS mobile app showing a live deal and approval timeline"/><div className="continuity-note note-one"><Check /><span><small>FINANCE APPROVAL</small><b>Synced just now</b></span></div><div className="continuity-note note-two"><Smartphone /><span><small>CONTINUE ON MOBILE</small><b>Q-1048 is live</b></span></div></div></section>
      <section className="voice-section"><div className="voice-visual"><div className={`voice-disc ${listening ? "listening" : ""}`}><div className="voice-rings" aria-hidden="true"><i /><i /><i /></div><AudioWaveform /><span>DEALOS / VOICE</span></div><div className="voice-transcript"><small>{listening ? "LISTENING · LIVE DEAL Q-1048" : "VOICE AGENT · READY"}</small><p>{listening ? "“What is blocking the Aranya deal?”" : "Ask DealOS before the next meeting."}</p><div><span>{listening ? "Finance review is pending. The service discount exceeds policy by 8 points." : "Context, policy, inventory, and approvals—without opening another tab."}</span></div></div></div><div className="voice-copy"><span className="section-index inverse">04 / TALK TO THE RECORD</span><h2>Ask the deal.<br /><em>Hear the answer.</em></h2><p>The voice agent reads the same governed record as your team. It can summarize risk, identify the next reviewer, and prepare you for the call without inventing a second source of truth.</p><button className={`voice-button ${listening ? "active" : ""}`} onClick={() => setListening(!listening)} aria-pressed={listening}><Mic />{listening ? "Stop listening" : "Try the voice agent"}<span>{listening ? "LIVE" : "PRESS TO SPEAK"}</span></button></div></section>
      <section className="proof-section" id="proof"><div className="proof-watermark" aria-hidden="true">CONTROL / WITHOUT THE CHASE</div><div className="section-intro proof-intro"><span className="section-index">05 / WORK THAT EXPLAINS ITSELF</span><h2>See the rule.<br /><em>See the reason.</em></h2><p>The interface stays quiet until something needs attention—then it shows exactly what changed and what happens next.</p></div><div className="proof-grid"><article className="proof-frame proof-risk"><span className="frame-coordinate">01 — RISK</span><div className="proof-label"><span>BLENDED RISK</span><ShieldCheck /></div><strong>8.0</strong><small>points above ceiling</small><div className="risk-bars"><span><i />Hardware · within policy</span><span><i />Services · finance review</span><span><i />Support · within policy</span></div><p>One thin-margin line cannot disappear inside the average.</p></article><article className="proof-frame proof-route"><span className="frame-coordinate">02 — STOCK</span><div className="proof-label"><span>FULFILLMENT PREVIEW</span><Boxes /></div><div className="mini-map"><span className="origin">ORDER<br /><b>24</b></span><i /><span>MUMBAI<br /><b>18</b></span><i /><span>PUNE<br /><b>6</b></span></div><div className="proof-summary"><span>2 shipments</span><span>₹27,300 estimated</span><b>0 backordered</b></div></article><article className="proof-frame proof-bill"><span className="frame-coordinate">03 — BILLING</span><div className="proof-label"><span>HYBRID BILLING</span><ReceiptText /></div><div className="bill-row"><span>Hardware + service<small>One-time invoice</small></span><b>₹1,16,16,000</b></div><div className="bill-row"><span>Priority support<small>Monthly schedule</small></span><b>₹1,04,000<em>/mo</em></b></div><div className="bill-timeline"><i /><i /><i /><i /><span>OCT</span><span>NOV</span><span>DEC</span><span>JAN</span></div></article><article className="proof-frame proof-portal"><span className="frame-coordinate">04 — PORTAL</span><div className="proof-label"><span>CUSTOMER PORTAL</span><FileText /></div><blockquote>“Can we move the service discount to 18% if we confirm this week?”</blockquote><div className="portal-response"><span>Terms changed</span><b>Reapproval started automatically</b></div><p>Negotiation stays on the record—not in an email thread.</p></article></div></section>
      <section className="audit-section"><div><span className="section-index inverse">06 / ACCOUNTABILITY BY DEFAULT</span><h2>Nothing important<br />becomes a mystery.</h2></div><div className="audit-list">{[["10:18", "Jordan submitted revision 06", "Commercial terms frozen"], ["10:24", "Maya approved the exception", "Reason attached"], ["10:31", "Finance review requested", "Policy v3.2 applied"], ["10:42", "Stock preview refreshed", "24 units available"]].map(([time, event, detail]) => <div key={time}><time>{time}</time><i><Check /></i><span><b>{event}</b><small>{detail}</small></span></div>)}</div><div className="audit-progress" aria-hidden="true"><i /></div></section>
      <section className="ledger-outro"><span className="section-index">THE NEXT DEAL STARTS HERE</span><h2><span>LESS CHASING.</span><span>MORE CERTAINTY.</span></h2><div><p>A single, accountable path from first quote to final payment.</p><a className="signal-button" href="/sign-up">Create your organization <ArrowUpRight /></a></div></section>
    </main>
    <footer className="ledger-footer"><Brand /><p>One record. Every decision.</p><a href="/sign-in">Enter workspace <ArrowUpRight /></a><button aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? <Play /> : <Pause />}{paused ? "Resume motion" : "Pause motion"}</button><span className="ledger-footer-meta"><i>© {new Date().getFullYear()} DealOS</i><b>Made with <em>♥</em> by Amartya, Sanket, Hitesh &amp; Aryan.</b></span></footer>
  </div>;
}
